# Generated by Django 5.2.8 on 2025-12-02 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('property', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('gp_pic', models.CharField(max_length=100)),
                ('date_in', models.DateField()),
                ('status_kanban', models.CharField(choices=[('lead_generation', 'Lead Generation'), ('follow_up', 'Follow Up'), ('quotation', 'Quotation'), ('deals', 'Deals'), ('onboarding', 'Onboarding'), ('retention', 'Retention')], default='lead_generation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_gp', models.CharField(max_length=100)),
                ('pic_lead', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('objective', models.CharField(default='Sales & Leads', max_length=200)),
                ('fu_type', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_gp', models.CharField(max_length=100)),
                ('pic_lead', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('objective', models.CharField(default='Sales & Leads', max_length=200)),
                ('meeting_type', models.CharField(max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('mom', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
