# Generated by Django 5.2.8 on 2025-12-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
