# Generated by Django 5.2.8 on 2025-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='stage',
            field=models.CharField(default='Follow Up', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='stage',
            field=models.CharField(default='Follow Up', max_length=100),
        ),
    ]
