# Generated by Django 5.2.8 on 2025-12-31 04:24

import django.db.models.deletion
import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_followup_stage_meeting_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.CharField(default=leads.models.generate_deal_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('deal_type', models.CharField(choices=[('New Deal', 'New Deal'), ('Migration', 'Migration'), ('Update Package', 'Update Package'), ('Refreshment Training', 'Refreshment Training'), ('Upselling', 'Upselling'), ('Room Update', 'Room Update')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('room', models.IntegerField(default=0)),
                ('project_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('nik_npwp', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('link_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_issued', models.BooleanField(default=False)),
                ('subscribe_changed', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('bukti_payment', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('pic_penerima_bukti_bayar', models.CharField(blank=True, max_length=100, null=True)),
                ('is_partial_payment', models.BooleanField(default=False)),
                ('link_payment_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('is_invoice_send_to_customer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='DealDetail',
            fields=[
                ('deal_detail_id', models.CharField(default=leads.models.generate_deal_detail_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('product_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product_amount_by', models.CharField(max_length=50)),
                ('initiation', models.CharField(max_length=255)),
                ('initiation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='leads.deal')),
            ],
        ),
    ]
