# Generated by Django 5.2.8 on 2025-12-31 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_deal_dealdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='pic_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.leadpic'),
        ),
    ]
