# Generated by Django 5.2.8 on 2026-01-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_deal_pic_lead'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deal',
            table='deal',
        ),
        migrations.AlterModelTable(
            name='dealdetail',
            table='deal_detail',
        ),
        migrations.AlterModelTable(
            name='followup',
            table='follow_up',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='lead',
        ),
        migrations.AlterModelTable(
            name='leadpic',
            table='lead_pic',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meeting',
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='quotation',
        ),
    ]
