# Generated by Django 5.2.8 on 2026-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_deal_table_alter_dealdetail_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_or_affiliate_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
