# Generated by Django 5.2.8 on 2026-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_commission_amount_lead_edited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='longitude',
        ),
        migrations.AddField(
            model_name='lead',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
