# Generated by Django 5.2.8 on 2026-01-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_meeting_latitude_remove_meeting_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealdetail',
            old_name='initiation',
            new_name='product_initiation',
        ),
        migrations.RenameField(
            model_name='dealdetail',
            old_name='initiation_amount',
            new_name='product_initiation_amount',
        ),
        migrations.RenameField(
            model_name='dealdetail',
            old_name='product_amount_by',
            new_name='product_initiation_amount_by',
        ),
        migrations.RemoveField(
            model_name='dealdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dealdetail',
            name='product_amount',
        ),
    ]
