# Generated by Django 4.2.27 on 2026-01-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_meeting_latitude_remove_meeting_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_by',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
