# Generated by Django 4.2.27 on 2026-01-08 03:36

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_deal_deal_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealdetail',
            old_name='initiation',
            new_name='product_initiation',
        ),
        migrations.RenameField(
            model_name='dealdetail',
            old_name='initiation_amount',
            new_name='product_initiation_amount',
        ),
        migrations.RenameField(
            model_name='dealdetail',
            old_name='product_amount_by',
            new_name='product_initiation_amount_by',
        ),
        migrations.RemoveField(
            model_name='dealdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dealdetail',
            name='product_amount',
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.CharField(default=leads.models.generate_training_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('pic_gp', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField(blank=True, null=True)),
                ('training_type', models.CharField(max_length=100)),
                ('periode', models.CharField(max_length=100)),
                ('module_in_charge', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.deal')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'db_table': 'training',
            },
        ),
        migrations.CreateModel(
            name='SetupData',
            fields=[
                ('setup_id', models.CharField(default=leads.models.generate_setup_data_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('pic_gp', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('setup_type', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.deal')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'db_table': 'setup_data',
            },
        ),
    ]
