# Generated by Django 5.2.8 on 2026-01-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_deal_deal_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealdetail',
            old_name='initiation',
            new_name='product_initiation',
        ),
        migrations.RenameField(
            model_name='dealdetail',
            old_name='initiation_amount',
            new_name='product_initiation_amount',
        ),
        migrations.RenameField(
            model_name='dealdetail',
            old_name='product_amount_by',
            new_name='product_initiation_amount_by',
        ),
        migrations.RemoveField(
            model_name='dealdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dealdetail',
            name='product_amount',
        ),
    ]
