# Generated by Django 5.2.8 on 2026-01-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rename_initiation_dealdetail_product_initiation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='account_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='management',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
